export const SET_LOGIN_FLAG = 'SET_LOGIN_FLAG'
export const SET_LOADING_FLAG = 'SET_LOADING_FLAG'

export const SET_LOGIN_LOADING_FLAG = 'SET_LOGIN_LOADING_FLAG'

export const INIT_TEST = 'INIT_TEST'
export const INIT_UPLOAD_STATE = 'INIT_UPLOAD_STATE'
export const SET_UPLOAD_FILE_INFO_LIST = 'SET_UPLOAD_FILE_INFO_LIST'
export const SET_UPLOAD_LOADING_FLAG = 'SET_UPLOAD_LOADING_FLAG'
export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS'
export const SET_RESULT_MESSAGE = 'SET_RESULT_MESSAGE'